# Generated by Django 3.2.9 on 2022-02-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='countries/about/', verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'About image',
                'verbose_name_plural': 'About images',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_logo', models.ImageField(upload_to='countries/logo/', verbose_name='Country logo')),
                ('country_name', models.CharField(max_length=255, verbose_name='Country name')),
                ('banner_image', models.ImageField(upload_to='countries/banner/', verbose_name='Banner image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('about_images', models.ManyToManyField(related_name='countries', to='countries.AboutImage', verbose_name='About images')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ('-created',),
            },
        ),
    ]
