# Generated by Django 3.2.9 on 2022-02-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='countries/about/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'AboutImage',
                'verbose_name_plural': 'AboutImages',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
                ('banner_title', models.CharField(max_length=255)),
                ('banner_sub_title', models.TextField(blank=True)),
                ('banner_image', models.ImageField(upload_to='countries/banner/')),
                ('about_text', models.TextField(blank=True)),
                ('advantage_1', models.TextField(blank=True)),
                ('advantage_2', models.TextField(blank=True)),
                ('advantage_3', models.TextField(blank=True)),
                ('advantage_4', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('about_image', models.ManyToManyField(related_name='countries', to='countries.AboutImage')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ('-created',),
            },
        ),
    ]
