# Generated by Django 3.2.9 on 2022-02-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutimage',
            name='image',
            field=models.ImageField(upload_to='countries/about/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='country',
            name='about_images',
            field=models.ManyToManyField(related_name='countries', to='countries.AboutImage', verbose_name='About Images'),
        ),
        migrations.AlterField(
            model_name='country',
            name='banner_image',
            field=models.ImageField(upload_to='countries/banner/', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_logo',
            field=models.ImageField(upload_to='countries/logo/', verbose_name='Country Logo'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=255, verbose_name='Country Name'),
        ),
    ]
