# Generated by Django 3.2.9 on 2022-02-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutimage',
            options={'ordering': ('-created',), 'verbose_name': 'About Image', 'verbose_name_plural': 'About Images'},
        ),
    ]
