# Generated by Django 3.2.9 on 2022-02-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='seo_text',
            field=models.TextField(blank=True, null=True, verbose_name='Counter SEO text'),
        ),
    ]
