# Generated by Django 3.2.9 on 2022-02-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_seo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='seo_text',
            field=models.TextField(blank=True, null=True, verbose_name='SEO text'),
        ),
    ]
