# Generated by Django 3.2.9 on 2022-02-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_aboutimage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='about_text',
        ),
        migrations.RemoveField(
            model_name='country',
            name='advantage_1',
        ),
        migrations.RemoveField(
            model_name='country',
            name='advantage_2',
        ),
        migrations.RemoveField(
            model_name='country',
            name='advantage_3',
        ),
        migrations.RemoveField(
            model_name='country',
            name='advantage_4',
        ),
        migrations.RemoveField(
            model_name='country',
            name='banner_sub_title',
        ),
        migrations.RemoveField(
            model_name='country',
            name='banner_title',
        ),
    ]
