# Generated by Django 3.2.9 on 2022-02-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_auto_20220206_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_logo',
            field=models.ImageField(default=1, upload_to='countries/logo/'),
            preserve_default=False,
        ),
    ]
