# Generated by Django 3.2.9 on 2021-11-08 03:37

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_country_university'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={'ordering': ('-created',), 'verbose_name': 'Counter', 'verbose_name_plural': 'Counters'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('-created',), 'verbose_name': 'Study place', 'verbose_name_plural': 'Study places'},
        ),
        migrations.AlterModelOptions(
            name='partnerlogo',
            options={'ordering': ('-created',), 'verbose_name': 'Partner Logo', 'verbose_name_plural': 'Partners Logo'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ('-created',), 'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.RemoveField(
            model_name='counter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='number',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.RemoveField(
            model_name='partnerlogo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='partnerlogo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='university',
            name='country',
        ),
        migrations.RemoveField(
            model_name='university',
            name='name',
        ),
        migrations.CreateModel(
            name='UniversityTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='app.country', verbose_name='Country')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.university')),
            ],
            options={
                'verbose_name': 'University Translation',
                'db_table': 'app_university_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases = (parler.models.TranslatableModel, models.Model)
        ),
        migrations.CreateModel(
            name='PartnerLogoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('image', models.ImageField(upload_to='logos/')),
                ('name', models.CharField(max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.partnerlogo')),
            ],
            options={
                'verbose_name': 'Partner Logo Translation',
                'db_table': 'app_partnerlogo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases = (parler.models.TranslatableModel, models.Model)
        ),
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.country')),
            ],
            options={
                'verbose_name': 'Study place Translation',
                'db_table': 'app_country_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases = (parler.models.TranslatableModel, models.Model)
        ),
        migrations.CreateModel(
            name='CounterTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='app.counter')),
            ],
            options={
                'verbose_name': 'Counter Translation',
                'db_table': 'app_counter_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases = (parler.models.TranslatableModel, models.Model)
        ),
    ]
