# Generated by Django 3.2.9 on 2021-11-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='phone',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='form',
            name='phone_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
