# Generated by Django 3.2.9 on 2022-02-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220208_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'SEO text',
                'verbose_name_plural': 'SEO texts',
                'ordering': ('-created',),
            },
        ),
    ]
