# Generated by Django 3.2.9 on 2022-02-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_seotext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeoText',
        ),
    ]
