# Generated by Django 3.2.9 on 2022-02-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_seotext'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Source'),
        ),
    ]
