# Generated by Django 3.2.9 on 2022-05-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_form_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='additional',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional'),
        ),
    ]
