# Generated by Django 3.2.9 on 2022-02-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
                ('banner_title', models.CharField(max_length=255)),
                ('banner_sub_title', models.TextField(blank=True)),
                ('about_text', models.TextField(blank=True)),
                ('advantage_1', models.TextField(blank=True)),
                ('advantage_2', models.TextField(blank=True)),
                ('advantage_3', models.TextField(blank=True)),
                ('advantage_4', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Country Translation',
                'verbose_name_plural': 'Country Translations',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PartnerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255)),
                ('foundation_year', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=255)),
                ('about_text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Partner Translation',
                'verbose_name_plural': 'Partner Translations',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TranslationLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Translation Language',
                'verbose_name_plural': 'Translation Languages',
                'ordering': ('-created',),
            },
        ),
    ]
