# Generated by Django 3.2.9 on 2022-02-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_auto_20220206_1137'),
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrytranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_translations', to='countries.country'),
        ),
    ]
