# Generated by Django 3.2.9 on 2022-02-08 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translations', '0001_initial'),
        ('universities', '0001_initial'),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertranslation',
            name='counters',
            field=models.ManyToManyField(related_name='partner_translations', to='universities.Counter'),
        ),
        migrations.AddField(
            model_name='partnertranslation',
            name='faculties',
            field=models.ManyToManyField(related_name='partner_translations', to='universities.Faculty'),
        ),
        migrations.AddField(
            model_name='partnertranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_translations', to='translations.translationlanguage'),
        ),
        migrations.AddField(
            model_name='partnertranslation',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_translations', to='universities.partner'),
        ),
        migrations.AddField(
            model_name='partnertranslation',
            name='partner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_translations', to='universities.partnertype'),
        ),
        migrations.AddField(
            model_name='countrytranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_translations', to='countries.country'),
        ),
        migrations.AddField(
            model_name='countrytranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_translations', to='translations.translationlanguage'),
        ),
    ]
