# Generated by Django 3.2.9 on 2022-02-10 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('universities', '0001_initial'),
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertranslation',
            name='counters',
            field=models.ManyToManyField(related_name='partner_translations', to='universities.Counter', verbose_name='Counters'),
        ),
        migrations.AddField(
            model_name='partnertranslation',
            name='faculties',
            field=models.ManyToManyField(related_name='partner_translations', to='universities.Faculty', verbose_name='Faculties'),
        ),
        migrations.AddField(
            model_name='partnertranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_translations', to='translations.translationlanguage', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='partnertranslation',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_translations', to='universities.partner', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='partnertranslation',
            name='partner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_translations', to='universities.partnertype', verbose_name='Partner type'),
        ),
        migrations.AddField(
            model_name='countrytranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_translations', to='countries.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='countrytranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_translations', to='translations.translationlanguage', verbose_name='Language'),
        ),
    ]
