# Generated by Django 3.2.9 on 2022-02-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
        ('translations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertranslation',
            name='programs',
            field=models.ManyToManyField(related_name='partner_translations', to='universities.Program', verbose_name='Programs'),
        ),
    ]
