# Generated by Django 3.2.9 on 2022-02-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20220208_1833'),
        ('universities', '0001_initial'),
        ('translations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrytranslation',
            name='about_text',
            field=models.TextField(blank=True, verbose_name='About Text'),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='advantage_1',
            field=models.TextField(blank=True, verbose_name='Advantage 1'),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='advantage_2',
            field=models.TextField(blank=True, verbose_name='Advantage 2'),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='advantage_3',
            field=models.TextField(blank=True, verbose_name='Advantage 3'),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='advantage_4',
            field=models.TextField(blank=True, verbose_name='Advantage 4'),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='banner_sub_title',
            field=models.TextField(blank=True, verbose_name='Banner Subtitle'),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='banner_title',
            field=models.CharField(max_length=255, verbose_name='Banner Title'),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_translations', to='countries.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='country_name',
            field=models.CharField(max_length=255, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_translations', to='translations.translationlanguage', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='partnertranslation',
            name='about_text',
            field=models.TextField(blank=True, verbose_name='About Text'),
        ),
        migrations.AlterField(
            model_name='partnertranslation',
            name='counters',
            field=models.ManyToManyField(related_name='partner_translations', to='universities.Counter', verbose_name='Counters'),
        ),
        migrations.AlterField(
            model_name='partnertranslation',
            name='faculties',
            field=models.ManyToManyField(related_name='partner_translations', to='universities.Faculty', verbose_name='Faculties'),
        ),
        migrations.AlterField(
            model_name='partnertranslation',
            name='foundation_year',
            field=models.CharField(max_length=255, verbose_name='Foundation Year'),
        ),
        migrations.AlterField(
            model_name='partnertranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_translations', to='translations.translationlanguage', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='partnertranslation',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='partnertranslation',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_translations', to='universities.partner', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='partnertranslation',
            name='partner_name',
            field=models.CharField(max_length=255, verbose_name='Partner Name'),
        ),
        migrations.AlterField(
            model_name='partnertranslation',
            name='partner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_translations', to='universities.partnertype', verbose_name='Partner Type'),
        ),
        migrations.AlterField(
            model_name='partnertranslation',
            name='payment',
            field=models.CharField(max_length=255, verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='translationlanguage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
