# Generated by Django 3.2.9 on 2022-02-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_auto_20220206_1137'),
        ('translations', '0002_alter_countrytranslation_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnertranslation',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_translations', to='universities.partner'),
        ),
    ]
