# Generated by Django 3.2.9 on 2022-02-16 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_partnertranslation_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrytranslation',
            name='slug',
        ),
    ]
