# Generated by Django 3.2.9 on 2022-02-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_alter_partnertranslation_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationlanguage',
            old_name='language',
            new_name='title',
        ),
    ]
