# Generated by Django 3.2.9 on 2022-02-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0004_rename_language_translationlanguage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnertranslation',
            name='counters',
        ),
        migrations.RemoveField(
            model_name='partnertranslation',
            name='faculties',
        ),
        migrations.RemoveField(
            model_name='partnertranslation',
            name='language',
        ),
        migrations.RemoveField(
            model_name='partnertranslation',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='partnertranslation',
            name='partner_type',
        ),
        migrations.DeleteModel(
            name='CountryTranslation',
        ),
        migrations.DeleteModel(
            name='PartnerTranslation',
        ),
        migrations.DeleteModel(
            name='TranslationLanguage',
        ),
    ]
