# Generated by Django 3.2.9 on 2022-02-08 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_alter_partner_country'),
        ('translations', '0006_countrytranslation_translationlanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255)),
                ('foundation_year', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('payment', models.CharField(max_length=255)),
                ('about_text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('counters', models.ManyToManyField(related_name='partner_translations', to='universities.Counter')),
                ('faculties', models.ManyToManyField(related_name='partner_translations', to='universities.Faculty')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_translations', to='translations.translationlanguage')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.partner')),
                ('partner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_translations', to='universities.partnertype')),
            ],
            options={
                'verbose_name': 'Partner Translation',
                'verbose_name_plural': 'Partner Translations',
                'ordering': ('-created',),
            },
        ),
    ]
