# Generated by Django 3.2.9 on 2022-02-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0007_partnertranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnertranslation',
            name='partner_type',
        ),
    ]
