# Generated by Django 3.2.9 on 2022-02-08 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_remove_partner_partner_type'),
        ('translations', '0008_remove_partnertranslation_partner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertranslation',
            name='partner_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='universities.partnertype'),
            preserve_default=False,
        ),
    ]
