# Generated by Django 3.2.9 on 2022-02-08 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_remove_partner_partner_type'),
        ('translations', '0009_partnertranslation_partner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnertranslation',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_translations', to='universities.partner'),
        ),
        migrations.AlterField(
            model_name='partnertranslation',
            name='partner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_translations', to='universities.partnertype'),
        ),
    ]
