# Generated by Django 3.2.9 on 2022-02-08 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_rename_about_image_country_about_images'),
        ('translations', '0010_auto_20220208_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrytranslation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_translations', to='countries.country'),
        ),
    ]
