# Generated by Django 3.2.9 on 2022-02-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_slug',
            field=models.SlugField(default='partner', help_text="Define the partner's URL slug. Only lowercase and _ instead of space.", max_length=40, verbose_name='Partner slug'),
        ),
    ]
