# Generated by Django 3.2.9 on 2022-02-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20220208_1833'),
        ('translations', '0003_auto_20220208_1833'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='counter_text',
            field=models.TextField(blank=True, verbose_name='Counter Text'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_value',
            field=models.CharField(max_length=255, verbose_name='Counter Value'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='about_video_url',
            field=models.URLField(verbose_name='About Video URL'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='countries.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=models.ImageField(upload_to='universities/image/', verbose_name='Partner Image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_name',
            field=models.CharField(max_length=255, verbose_name='Partner Name'),
        ),
        migrations.AlterField(
            model_name='partnertype',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_types', to='translations.translationlanguage', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='partnertype',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
