# Generated by Django 3.2.9 on 2022-08-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_partner_partner_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_program',
            field=models.BooleanField(default=False),
        ),
    ]
