# Generated by Django 3.2.9 on 2022-02-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_partner_partner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='about_text',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='counters',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='faculties',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='foundation_year',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='location',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='partner_type',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='payment',
        ),
    ]
