# Generated by Django 3.2.9 on 2022-02-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_auto_20220206_1137'),
        ('universities', '0004_auto_20220206_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='countries.country'),
        ),
    ]
