# Generated by Django 3.2.9 on 2022-02-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_auto_20220208_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='partner_type',
        ),
    ]
